version: '3.5'
services:
    php:
        build: ./docker/php-fpm
        container_name: php-fpm
        volumes:
            - ./:/var/www:cached
        links:
            - mysql


    nginx:
        build: ./docker/nginx
        container_name: nginx
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./:/var/www:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        links:
            - php


    mysql:
        build: ./docker/mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
        - "3306:3306"